content:
  value: '<p><a href="" https:="" digitalia.phil.muni.cz="" o-nas="" lindatclariah-cz=""><img src="/themes/custom/islandora_muni/images/LINDAT-CLARIAH-cz.svg" alt="LINDAT/CLALRIAH" width="120" height="69"></a> <a href="https://it.muni.cz/cs/cit-ff"><img src="/themes/custom/islandora_muni/images/logo-cit-barva.svg" alt="CIT MUNI ARTS" width="208" height="69"></a></p>'
  format: full_html
