_core:
  default_config_hash: 6PQBSsRyX81lTFgc44CgmHotr19DK4tVapnDUDm2pO0
langcode: en
media_fields: 'image:field_media_image;file:field_media_file'
reference_fields: field_member_of
media_delimiter: ;
reference_delimiter: ^
double_fields: ''
triple_fields: ''
