_core:
  default_config_hash: Yo9I-9cCMhnGRddog63IHfaD1MW-X7LIiPZnK8KLvEU
doi_datacite_api_endpoint: 'https://api.datacite.org/dois'
doi_datacite_prefix: '10.58063'
doi_datacite_suffix_source: auto
doi_datacite_username: GCNC.GHGVVX
doi_datacite_password: ''
doi_datacite_creators_mapping: ''
doi_datacite_publisher_mapping: ''
doi_datacite_publicationyear_mapping: field_edtf_date_issued
doi_datacite_creators_mapping_dataset: ':unkn'
doi_datacite_publisher_mapping_dataset: ':unkn'
doi_datacite_publicationyear_mapping_dataset: ':unkn'
