_core:
  default_config_hash: ZdPdgeYPxAPoTIlcCxW_tRoExm87onUdOjF3ZY2gfto
rest_oai_pmh:
  entity_type: node
view_displays:
  'ccmm_oai_pmh:all_datasets': 'ccmm_oai_pmh:all_datasets'
support_sets: 0
mapping_source: rdf
repository_name: 'Metasys Digitalia MUNI ARTS'
repository_email: ff-digitalia-admins@group.muni.cz
expiration: '3600'
metadata_map_plugins:
  -
    label: ccmm-xml
    value: ccmm
  -
    label: oai_dc
    value: dublin_core_metatag
  -
    label: oai_raw
    value: ''
  -
    label: mods
    value: ''
cache_technique: liberal_cache
mods_view:
  view_machine_name: ''
  view_display_name: ''
